name: Android CI/CD Workflow

on:
  push:
    branches: [ "main", "dev", "release/**" ]
    paths-ignore:
      - '**.md'
      - '.github/workflows/**'
  pull_request:
    branches: [ "main", "dev" ]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

env:
  # JDK & Gradle
  BUILD_JAVA_VERSION: '17'
  BUILD_JAVA_DIST: 'adopt'
  GRADLE_OPTS: -Dorg.gradle.jvmargs=-Xmx4096m

  # Android SDK
  ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
  ANDROID_BUILD_TOOLS_VERSION: '34.0.0'
  ANDROID_SDK_PLATFORM_VERSION: '34'

  # Maven Central / Signing
  ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MVN_USERNAME }}
  ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MVN_PASSWORD }}
  ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.MVN_SIGNING_KEY }}
  ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.MVN_SIGNING_KEY_ID }}
  ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.MVN_SIGNING_KEY_PASSWORD }}

jobs:
  build:
    name: Build APKs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [debug, release]

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.BUILD_JAVA_DIST }}
          java-version: ${{ env.BUILD_JAVA_VERSION }}

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: ${{ env.ANDROID_SDK_PLATFORM_VERSION }}
          build-tools: ${{ env.ANDROID_BUILD_TOOLS_VERSION }}

      - name: Grant Gradle permissions
        run: chmod +x ./gradlew

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}

      - name: Build ${{ matrix.build_type }} APK
        run: ./gradlew :app:assemble${{ matrix.build_type^ }} --no-daemon --stacktrace

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.build_type }}-apk
          path: app/build/outputs/apk/${{ matrix.build_type }}/*.apk

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.BUILD_JAVA_VERSION }}
          distribution: ${{ env.BUILD_JAVA_DIST }}

      - name: Grant Gradle permissions
        run: chmod +x ./gradlew

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}
          restore-keys: gradle-${{ runner.os }}

      - name: Run Tests
        run: ./gradlew test --stacktrace

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: '**/build/reports/tests/'

  publish:
    name: Publish to Maven Central
    runs-on: ubuntu-latest
    needs: [ build, test ]
    if: |
      github.ref == 'refs/heads/main' &&
      github.event_name != 'pull_request' &&
      needs.build.result == 'success' &&
      needs.test.result == 'success'

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.BUILD_JAVA_VERSION }}
          distribution: ${{ env.BUILD_JAVA_DIST }}

      - name: Grant Gradle permissions
        run: chmod +x ./gradlew

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}
          restore-keys: gradle-${{ runner.os }}

      - name: Publish
        run: ./gradlew publish --no-daemon --stacktrace

      - name: Upload Maven Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: maven-artifacts
          path: '**/build/publications/**'