name: Android Build & Release

on:
  push:
    branches: [ "main", "dev", "release/**" ]
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:

env:
  BUILD_JAVA_VERSION: 17
  BUILD_JAVA_DIST: adopt
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4096m"
  ANDROID_BUILD_TOOLS_VERSION: "34.0.4"
  ANDROID_SDK_PLATFORM_VERSION: "34"
  ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk

jobs:
  build:
    name: Build APKs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.BUILD_JAVA_DIST }}
          java-version: ${{ env.BUILD_JAVA_VERSION }}

      - name: Set ANDROID_SDK_ROOT environment variable
        run: echo "ANDROID_SDK_ROOT=${{ env.ANDROID_SDK_ROOT }}" >> $GITHUB_ENV

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: ${{ env.ANDROID_SDK_PLATFORM_VERSION }}
          build-tools: ${{ env.ANDROID_BUILD_TOOLS_VERSION }}
          cache: true

      - name: List Android SDK directories for debug
        run: ls -la ${{ env.ANDROID_SDK_ROOT }}

      - name: Cache Gradle wrapper and caches
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}

      - name: Grant permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Show Java and Gradle versions
        run: |
          java -version
          ./gradlew --version

      - name: Build debug APK
        run: ./gradlew :app:assembleDebug --no-daemon --info

      - name: Upload debug APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/*.apk