name: Android Build & Release

on:
  push:
    branches: [ "main", "dev", "release/**" ]
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:

env:
  BUILD_JAVA_VERSION: 17
  BUILD_JAVA_DIST: adopt
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4096m"
  ANDROID_BUILD_TOOLS_VERSION: "34.0.4"
  ANDROID_SDK_PLATFORM_VERSION: "34"

jobs:
  build:
    name: Build APKs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.BUILD_JAVA_DIST }}
          java-version: ${{ env.BUILD_JAVA_VERSION }}

      - name: Install required Android SDK packages manually
        run: |
          sudo mkdir -p /opt/android-sdk/cmdline-tools
          sudo curl -sSL https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -o cmdline-tools.zip
          sudo unzip -q cmdline-tools.zip -d /opt/android-sdk/cmdline-tools
          sudo mv /opt/android-sdk/cmdline-tools/cmdline-tools /opt/android-sdk/cmdline-tools/latest
          echo "ANDROID_HOME=/opt/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=/opt/android-sdk" >> $GITHUB_ENV
          echo "PATH=$PATH:/opt/android-sdk/cmdline-tools/latest/bin:/opt/android-sdk/platform-tools" >> $GITHUB_ENV
          sudo yes | /opt/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=/opt/android-sdk \
            "platform-tools" \
            "build-tools;${ANDROID_BUILD_TOOLS_VERSION}" \
            "platforms;android-${ANDROID_SDK_PLATFORM_VERSION}"

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}

      - name: Grant permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Show Java and Gradle versions
        run: |
          java -version
          ./gradlew --version

      - name: Build debug APK
        run: ./gradlew :app:assembleDebug --no-daemon --warning-mode all --info

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/*.apk